### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by dendisuhubdy** [bitwyre/template-rust#1]
I wonder how would you test a Rust repo

**Comment by Ujang360** [comment]
This is the test runner:
https://github.com/bitwyre/template-rust/commit/574e53752abedd706c844368b9cb85bba68f2108

And this is how we define test in the source file (**encouraged to do so**), but excludes it on build (the `mod` keyword):
https://github.com/bitwyre/template-rust/blob/574e53752abedd706c844368b9cb85bba68f2108/src/some_module.rs#L24-L33
